services:
  web:
    build: .
    volumes:
      - .:/api_status_aggregator
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=presentation.web.app:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1