services:
  web:
    build: .
    volumes:
      - .:/api_status_aggregator
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=presentation.web.app:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/status_dashboard
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.3
    environment:
      - POSTGRES_DB=status_dashboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: