[build]
builder = "dockerfile"

[deploy]
startCommand = "python docker-entrypoint.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
PORT = 5000
FLASK_ENV = "production"
FLASK_DEBUG = 0
LOG_LEVEL = "INFO"
CHECK_INTERVAL = 300